AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  furl-api-test

  Sample SAM Template for furl-api-test
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Architectures:
      - arm64

Resources:
  ServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: latency/
      Handler: server.lambdaHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: furl-api-test
          POWERTOOLS_METRICS_NAMESPACE: LatencyTest
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - server.ts
  ClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: latency/
      Handler: client.lambdaHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: furl-api-test
          POWERTOOLS_METRICS_NAMESPACE: LatencyTest
          URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - client.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ServerFunction:
    Description: "Server Lambda Function ARN"
    Value: !GetAtt ServerFunction.Arn
  ClientFunction:
    Description: "Client Lambda Function ARN"
    Value: !GetAtt ClientFunction.Arn

