version = 0.1
[default.deploy.parameters]
stack_name = "eb-test"
resolve_s3 = true
s3_prefix = "eb-test"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
